---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aap-controller-metrics
  labels:
    team: frontend
spec:
  namespaceSelector:
    matchNames:
      - aap
  selector:
    matchLabels:
      app.kubernetes.io/component: aap
      app.kubernetes.io/managed-by: aap-operator
  endpoints:
    - interval: 15s
      path: /api/controller/v2/metrics
      scheme: http
      basicAuth:
        username:
          name: aap-admin
          key: username
        password:
          name: aap-admin-password
          key: password
