---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-vaultwarden
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: grafana-admin-vaultwarden
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        GF_SECURITY_ADMIN_USER: "{{ .username }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/grafana-admin
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/grafana-admin
        property: password
