---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets-rhaap-portal
  namespace: aap-portal
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: secrets-rhaap-portal
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        aap-host-url: "{{ .aaphosturl }}"
        oauth-client-id: "{{ .oauthclientid }}"
        oauth-client-secret: "{{ .oauthclientsecret }}"
        aap-token: "{{ .aaptoken }}"
  data:
    - secretKey: aaphosturl
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/aap-portal
        property: aap-host-url
    - secretKey: oauthclientid
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/aap-portal
        property: oauth-client-id
    - secretKey: oauthclientsecret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/aap-portal
        property: oauth-client-secret
    - secretKey: aaptoken
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/aap-portal
        property: aap-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets-scm
  namespace: aap-portal
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: secrets-scm
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        github-token: "{{ .githubtoken }}"
  data:
    - secretKey: githubtoken
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/aap-portal
        property: github-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redhat-rhaap-portal-dynamic-plugins-registry-auth
  namespace: aap-portal
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: redhat-rhaap-portal-dynamic-plugins-registry-auth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        auth.json: |
          {
            "auths": {
              "registry.redhat.io": {
                "auth": "{{ .registryauth | trim | b64dec | trim | b64enc }}"
              }
            }
          }
  data:
    - secretKey: registryauth
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/aap-portal
        property: registry-auth-b64
