---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: monitoring-operator-group
spec:
  targetNamespaces:
  - monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator-subscription
  namespace: openshift-operators
spec:
  channel: v5
  name: grafana-operator
  installPlanApproval: Automatic
  source: community-operators
  sourceNamespace: openshift-marketplace
