---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apme-last-build-sha
  namespace: apme-dev
data:
  sha: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apme-operator-last-build-sha
  namespace: apme-dev
data:
  sha: ""
