---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apme-build-workspace
  namespace: apme-dev
  labels:
    tekton.dev/pipeline: apme-build
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-lvm-local-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apme-operator-build-workspace
  namespace: apme-dev
  labels:
    tekton.dev/pipeline: apme-operator-build
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-lvm-local-storage
  resources:
    requests:
      storage: 2Gi
