{{- if and .Values.apme.enabled .Values.apme.feedback.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-apme-secrets
  labels:
    app.kubernetes.io/name: apme
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{- if .Values.apme.feedback.githubRepo }}
  feedback-github-repo: {{ .Values.apme.feedback.githubRepo | quote }}
  {{- end }}
  {{- if .Values.apme.feedback.githubToken }}
  feedback-github-token: {{ .Values.apme.feedback.githubToken | quote }}
  {{- end }}
{{- end }}
