{{- if .Values.apme.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apme-gateway
  labels:
    app.kubernetes.io/name: apme
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 50060
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: apme
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
