---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apme-gcp-credentials
  namespace: apme
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: apme-gcp-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        service-account-key.json: "{{ .gcpsakey }}"
  data:
    - secretKey: gcpsakey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/apme-abbenay
        property: gcp-service-account-key
