{
 "title": "AAP Environment Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(aap_overall_status, job)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overall AAP Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aap_overall_status_value", "legendFormat": "{{status}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 4, "y": 0 },
   "repeat": "component",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (exported_service) (\n  (aap_service_node_status_value{status=\"good\"})\n  or\n  (0 - aap_service_node_status_value{status=\"failed\"})\n  or\n  (aap_service_node_status_value{status=\"degraded\"} * 0)\n)"
    }
   ]
  },
  {
   "title": "Redis Cluster Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aap_redis_cluster_status_value", "legendFormat": "{{cluster_state}}" }
   ]
  },
  {
   "title": "Redis Cluster Slots Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aap_redis_cluster_info_slots_fail",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Redis Cluster Slots Ok",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aap_redis_cluster_info_slots_ok",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Redis Cluster Slots Assigned",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aap_redis_cluster_info_slots_assigned",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Redis Cluster Known Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aap_redis_cluster_info_known_nodes",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Redis Cluster Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aap_redis_cluster_info_size", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Controller Instances",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "aap_controller_instance_running_value"
    }
   ]
  },
  {
   "title": "Redis Node Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "aap_redis_node_connected_value" }
   ]
  },
  {
   "title": "Hub Component Versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "aap_hub_component_info_value" }
   ]
  },
  {
   "title": "Hub DB Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aap_hub_database_connection_status_value",
     "legendFormat": "{{connected}}"
    }
   ]
  },
  {
   "title": "Hub Redis Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(connected) (aap_hub_redis_connection_status_value)",
     "legendFormat": "{{connected}}"
    }
   ]
  },
  {
   "title": "Online Content Apps",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "aap_hub_online_content_app_status_value"
    }
   ]
  },
  {
   "title": "Online Hub Workers",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "aap_hub_online_worker_status_value"
    }
   ]
  },
  {
   "title": "Online API Apps",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "aap_hub_online_api_app_status_value"
    }
   ]
  }
 ]
}