apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: prometheus-operator
type: Opaque
data:
  admin-user: cm9vdA==        # base64 for "root"
  admin-password: c3RhcnQ=    # base64 for "start"

