---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-admin-password
  namespace: aap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aap-admin-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/aap/admin-password
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-postgres-configuration-controller
  namespace: aap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: external-postgres-configuration-controller
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: secret/aap/postgres-controller
        property: host
    - secretKey: port
      remoteRef:
        key: secret/aap/postgres-controller
        property: port
    - secretKey: database
      remoteRef:
        key: secret/aap/postgres-controller
        property: database
    - secretKey: username
      remoteRef:
        key: secret/aap/postgres-controller
        property: username
    - secretKey: password
      remoteRef:
        key: secret/aap/postgres-controller
        property: password
    - secretKey: type
      remoteRef:
        key: secret/aap/postgres-controller
        property: type
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-postgres-configuration-eda
  namespace: aap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: external-postgres-configuration-eda
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: secret/aap/postgres-eda
        property: host
    - secretKey: port
      remoteRef:
        key: secret/aap/postgres-eda
        property: port
    - secretKey: database
      remoteRef:
        key: secret/aap/postgres-eda
        property: database
    - secretKey: username
      remoteRef:
        key: secret/aap/postgres-eda
        property: username
    - secretKey: password
      remoteRef:
        key: secret/aap/postgres-eda
        property: password
    - secretKey: type
      remoteRef:
        key: secret/aap/postgres-eda
        property: type
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-postgres-configuration-hub
  namespace: aap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: external-postgres-configuration-hub
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: secret/aap/postgres-hub
        property: host
    - secretKey: port
      remoteRef:
        key: secret/aap/postgres-hub
        property: port
    - secretKey: database
      remoteRef:
        key: secret/aap/postgres-hub
        property: database
    - secretKey: username
      remoteRef:
        key: secret/aap/postgres-hub
        property: username
    - secretKey: password
      remoteRef:
        key: secret/aap/postgres-hub
        property: password
    - secretKey: type
      remoteRef:
        key: secret/aap/postgres-hub
        property: type
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-postgres-configuration-gateway
  namespace: aap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: external-postgres-configuration-gateway
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: secret/aap/postgres-gateway
        property: host
    - secretKey: port
      remoteRef:
        key: secret/aap/postgres-gateway
        property: port
    - secretKey: database
      remoteRef:
        key: secret/aap/postgres-gateway
        property: database
    - secretKey: username
      remoteRef:
        key: secret/aap/postgres-gateway
        property: username
    - secretKey: password
      remoteRef:
        key: secret/aap/postgres-gateway
        property: password
    - secretKey: type
      remoteRef:
        key: secret/aap/postgres-gateway
        property: type
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-admin-password
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aap-admin-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/aap/admin-password
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aap-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/aap/admin
        property: username
