apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-instance
  namespace: openshift-gitops
spec:
  destination:
    namespace: aap
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    path: apps/aap/instances/
    targetRevision: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
