apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-pg-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    path: apps/aap/pg-operator/
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
