---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-monitoring
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  destination:
    namespace: aap
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    path: apps/aap/monitoring/
    targetRevision: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
