---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apme-fixes
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    path: apps/apme/fixes/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: apme
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
