---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apme
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/djdanielsson/ocp_lab.git
      targetRevision: apme
      ref: values
    - repoURL: https://github.com/ansible/apme.git
      targetRevision: main
      path: deploy/helm/apme
      helm:
        releaseName: apme
        apiVersions:
          - route.openshift.io/v1
        valueFiles:
          - $values/apps/apme/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apme
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
