# app-replicator.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-replicator
spec:
  project: default
  source:
    repoURL: 'https://helm.mittwald.de'
    chart: kubernetes-replicator
    targetRevision: 2.11.1
  destination:
    server: https://kubernetes.default.svc
    namespace: default # You can deploy it to any management namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
