apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-replicator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://helm.mittwald.de'
    chart: kubernetes-replicator
    targetRevision: 2.11.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
