---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-bitwarden
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    path: apps/external-secrets/bitwarden-provider/
    targetRevision: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
