apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: kubeshark
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    path: apps/kubeshark/
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
