---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    targetRevision: test
    path: apps/monitoring/operator/
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
