apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: openshift-gitops
spec:
  destination:
    namespace: prometheus-operator
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    path: apps/monitoring
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependsOn:
    - aap-instance
