apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-components
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    targetRevision: main
    path: apps/monitoring/components/
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically create the 'monitoring' namespace
