---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netobserv-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: netobserv
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/djdanielsson/ocp_lab.git
    path: apps/netobserv/instance/
    targetRevision: new
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
