---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-mcp-server-config
  namespace: ocp-mcp-server
  labels:
    app: ocp-mcp-server
data:
  config.toml: |
    port = "8080"
    bind_address = "0.0.0.0"
    log_level = 2
