---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: authentik
  namespace: authentik
spec:
  host: authentik.apps.ocp.new.lab.danielsson.us.com
  to:
    kind: Service
    name: authentik-server
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
