---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: graylog-admin-credentials
  namespace: graylog
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: graylog-admin-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        GRAYLOG_ROOT_USERNAME: "{{ .username }}"
        GRAYLOG_ROOT_PASSWORD_SHA2: "{{ .password | sha256sum }}"
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/graylog-admin
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/graylog-admin
        property: password
