apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ansiblecontroller-monitor
  labels:
    team: frontend
spec:
  namespaceSelector:
    matchNames:
      - aap
  selector:
    matchLabels:
      app.kubernetes.io/component: aap-api
  endpoints:
    - interval: 5s
      path: /api/controller/v2/metrics
      scheme: http
      basicAuth:
        username:
          name: aap-admin
          key: username
        password:
          name: aap-admin-password
          key: password
