---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-admin
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: aap-admin
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/aap-admin
        property: username
