---
apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: external-truenas-netdata
      metrics_path: /api/v1/allmetrics
      params:
        format: [prometheus]
      scrape_interval: 15s
      static_configs:
        - targets:
            - "192.168.2.82:20489"
          labels:
            instance: truenas
    - job_name: external-portainer-netdata
      metrics_path: /api/v1/allmetrics
      params:
        format: [prometheus]
      scrape_interval: 15s
      static_configs:
        - targets:
            - "192.168.2.213:19999"
          labels:
            instance: portainer
    - job_name: klipper
      scrape_interval: 30s
      metrics_path: /probe
      params:
        modules:
        - process_stats
        - job_queue
        - system_info
        - network_stats
        - directory_info
        - printer_objects
        - history
      static_configs:
        - targets:
            - "192.168.2.105:7125"
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: klipper-exporter.monitoring.svc.cluster.local:9101
    - job_name: klipper-exporter
      scrape_interval: 120s
      metrics_path: /metrics
      static_configs:
        - targets:
            - klipper-exporter.monitoring.svc.cluster.local:9101
