# kind: GrafanaDatasource
# apiVersion: grafana.integreatly.org/v1beta1
# metadata:
#   name: grafana-datasource
# spec:
#   datasource:
#     access: proxy
#     isDefault: true
#     jsonData:
#       timeInterval: 5s
#       tlsSkipVerify: true
#     name: prometheus
#     type: prometheus
#     url: 'https://thanos-querier.openshift-monitoring.svc:9091'
#   instanceSelector:
#     matchLabels:
#       dashboards: grafana
#   plugins:
#     - name: grafana-clock-panel
#       version: 1.3.0
kind: GrafanaDatasource
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  name: grafana-datasource
spec:
  datasource:
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: prometheus
    type: prometheus
    url: 'http://prometheus:9090'
  instanceSelector:
    matchLabels:
      dashboards: grafana
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
