kind: Grafana
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  labels:
    dashboards: grafana
    folders: grafana
  name: grafana
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
  # ingress:
  #   spec:
  #     rules:
  #       - host: grafana-monitoring.apps.ocp.lab.danielsson.us.com 
  #         http:
  #           paths:
  #             - path: /
  #               pathType: Prefix
  #               backend:
  #                 service:
  #                   name: grafana-service
  #                   port:
  #                     number: 3000
  # admin:
  #   existingSecret: grafana-admin-credentials
  #   userKey: admin-user
  #   passwordKey: admin-password

