apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque
data:
  admin-user: cm9vdA==        # base64 for "root"
  admin-password: c3RhcnQ=    # base64 for "start"
---
apiVersion: v1
kind: Secret
metadata:
  name: bearertoken
type: Opaque
stringData:
  secret: "YOUR_BEARER_TOKEN_HERE"

