---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth-secret
  annotations:
    kubernetes.io/service-account.name: grafana
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: bearertoken
type: Opaque
stringData:
  secret: "xk30dW1txefo7wu1Vvkirz6sGshLLU" # notsecret

