---
# This ServiceMonitor tells Prometheus where to find the metrics service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporters-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: postgres-exporters
  namespaceSelector:
    matchNames:
      - aap
  endpoints:
    - port: metrics-gateway
      interval: 15s
    - port: metrics-ctrl
      interval: 15s
    - port: metrics-hub
      interval: 15s
    - port: metrics-eda
      interval: 15s
