---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: monitoring-operator-group
  namespace: monitoring
spec:
  targetNamespaces:
  - monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-operator-subscription
  namespace: monitoring
spec:
  channel: 'beta'
  installPlanApproval: Automatic
  name: 'prometheus'
  source: 'redhat-operators'
  sourceNamespace: 'openshift-marketplace'