apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  to:
    kind: Service
    name: prometheus
    weight: 100
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
