# ---
# apiVersion: operators.coreos.com/v1
# kind: OperatorGroup
# metadata:
#   name: grafana-operator
#   namespace: grafana-operator
# spec:
#   targetNamespaces:
#   - grafana-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-operator-subscription
  namespace: monitoring
spec:
  channel: beta
  name: rhods-prometheus-operator
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
