apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ansiblecontroller-monitor
  labels:
    openshift.io/cluster-monitoring: 'true'
spec:
  namespaceSelector:
    matchNames:
      - aap
  selector:
    matchLabels:
      monitor: metrics
  endpoints:
    - interval: 5s
      path: /api/controller/v2/metrics
      scheme: http
      bearerTokenSecret:
        name: bearertoken
        key: secret
