---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-postgres
  namespace: quay-ephemeral
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: quay-postgres
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        POSTGRESQL_PASSWORD: "{{ .dbPassword }}"
        POSTGRESQL_ADMIN_PASSWORD: "{{ .dbPassword }}"
  data:
    - secretKey: dbPassword
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/quay-config
        property: DB_PASSWORD
