---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apme-operator-controller-manager
  namespace: apme-operator-system
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"apme-operator:latest","namespace":"apme-operator-system"},"fieldPath":"spec.template.spec.containers[?(@.name==\"manager\")].image"}]'
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: apme
            - name: LEADER_ELECTION_ID
              value: b760e4bf.ansible.com
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi
