---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: apme-operator
  namespace: apme-operator-system
  labels:
    app.kubernetes.io/name: apme-operator
spec:
  lookupPolicy:
    local: true
