---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - imagestream.yaml
  - buildconfig.yaml
  - install.yaml

images:
  - name: controller
    newName: image-registry.openshift-image-registry.svc:5000/apme/apme-operator
    newTag: latest

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: apme-operator-controller-manager
