---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orchestrator-postgres-secret
  namespace: automation-orchestrator
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: orchestrator-postgres-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        database: orchestrator
        username: orchestrator
        password: "{{ .password }}"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/postgres-orchestrator
        property: password
