---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-postgres-secret
  namespace: automation-orchestrator
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: temporal-postgres-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        database: temporal
        username: temporal
        password: "{{ .password }}"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/postgres-temporal
        property: password
