---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: netobserv-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: netobserv-operator
  startingCSV: network-observability-operator.v1.11.0
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
