apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: gitrunners
spec:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: REPO_URL
          value: "djdanielsson/config_as_code"
        - name: RUNNER_NAME
          value: ocp-runner
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-token
              key: token
        - name: LABELS
          value: ocp
        volumeMounts:
        - name: runner-home
          mountPath: /home/github
      volumes:
      - name: runner-home
        emptyDir: {}


