---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-login
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.external-secrets.svc.cluster.local:8087/list/object/items?search={{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.data[0].login.{{ .remoteRef.property }}"
      headers:
        Content-Type: application/json
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.external-secrets.svc.cluster.local:8087/list/object/items?search={{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.data[0].fields[?@.name==\"{{ .remoteRef.property }}\"].value"
      headers:
        Content-Type: application/json
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-notes
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.external-secrets.svc.cluster.local:8087/list/object/items?search={{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.data[0].notes"
      headers:
        Content-Type: application/json
