---
kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: aap-postgres
spec:
  managed:
    roles:
      - name: aap
        ensure: present
        login: true
      - name: automationgateway
        ensure: present
        login: true
        passwordSecret:
          name: external-postgres-configuration-gateway
      - name: automationhub
        ensure: present
        login: true
        passwordSecret:
          name: external-postgres-configuration-hub
      - name: automationcontroller
        ensure: present
        login: true
        passwordSecret:
          name: external-postgres-configuration-controller
      - name: automationeda
        ensure: present
        passwordSecret:
          name: external-postgres-configuration-eda
        login: true
      - name: metricsservice
        ensure: present
        login: true
        createdb: true
        passwordSecret:
          name: aap-metrics-postgres-configuration
      - name: ms_awx_readonly
        ensure: present
        login: true
        passwordSecret:
          name: external-metrics-readonly-configuration
      - name: orchestrator
        ensure: present
        login: true
        passwordSecret:
          name: ao-orchestrator-postgres-password
      - name: temporal
        ensure: present
        login: true
        passwordSecret:
          name: ao-temporal-postgres-password
  instances: 3
  switchoverDelay: 5
  replicationSlots:
    highAvailability:
      enabled: true
  logLevel: info
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      max_connections: "2000"
    synchronous:
      method: any
      number: 2
      dataDurability: preferred
  storage:
    size: 100Gi
  walStorage:
    size: 20Gi
