---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aap-admin-password
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: aap-admin-password
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/aap-admin
        property: password
