---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
spec:
  feature_flags:
    FEATURE_DISPATCHERD_ENABLED: True
  route_tls_termination_mechanism: Edge
  service_type: ClusterIP
  ingress_type: Route
  no_log: true
  redis_mode: cluster
  image_pull_policy: Always
  hostname: aap.apps.ocp.lab.danielsson.us.com
  admin_password_secret: aap-admin-password
  api:
    log_level: INFO
    replicas: 1
    resource_requirements:
      requests:
        cpu: 5m
        memory: 50Mi
  redis:
    resource_requirements:
      requests:
        cpu: 5m
        memory: 50Mi
  database:
    postgres_data_volume_init: false
    database_secret: external-postgres-configuration-gateway
  route_host: aap.apps.ocp.lab.danielsson.us.com
  hub:
    file_storage_access_mode: ReadWriteOnce
    postgres_configuration_secret: external-postgres-configuration-hub
    redis:
      resource_requirements:
        requests:
          cpu: 5m
          memory: 50Mi
    resource_manager:
      resource_requirements:
        requests:
          cpu: 50m
          memory: 250Mi
    api:
      resource_requirements:
        requests:
          cpu: 50m
          memory: 250Mi
    content:
      resource_requirements:
        requests:
          cpu: 50m
          memory: 250Mi
    web:
      resource_requirements:
        requests:
          cpu: 50m
          memory: 250Mi
    worker:
      resource_requirements:
        requests:
          cpu: 50m
          memory: 250Mi
  controller:
    postgres_configuration_secret: external-postgres-configuration-controller
    ee_resource_requirements:
      requests:
        cpu: 5m
        memory: 50Mi
    task_resource_requirements:
      requests:
        cpu: 5m
        memory: 50Mi
    web_resource_requirements:
      requests:
        cpu: 5m
        memory: 50Mi
    redis_resource_requirements:
      requests:
        cpu: 5m
        memory: 50Mi
    rsyslog_resource_requirements:
      requests:
        cpu: 5m
        memory: 50Mi
  eda:
    database:
        database_secret: external-postgres-configuration-eda
    activation_worker:
      resource_requirements:
        requests:
          cpu: 5m
          memory: 50Mi
    api:
      resource_requirements:
        requests:
          cpu: 5m
          memory: 50Mi
    default_worker:
      resource_requirements:
        requests:
          cpu: 5m
          memory: 50Mi
    event_stream: 
      resource_requirements:
        requests:
          cpu: 5m
          memory: 50Mi
    redis:
      resource_requirements:
        requests:
          cpu: 5m
          memory: 50Mi
    scheduler:
      resource_requirements:
        requests:
          cpu: 5m
          memory: 50Mi
    ui:
      resource_requirements:
        requests:
          cpu: 5m
          memory: 50Mi
