apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
spec:
  route_tls_termination_mechanism: Edge
  service_type: ClusterIP
  ingress_type: Route
  no_log: true
  redis_mode: cluster
  image_pull_policy: Always
  hostname: aap.apps.ocp.lab.danielsson.us.com
  hub:
    file_storage_access_mode: ReadWriteOnce
  api:
    log_level: INFO
    replicas: 1
  database:
    postgres_data_volume_init: false
  route_host: aap.apps.ocp.lab.danielsson.us.com

