---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gateway-database
spec:
  cluster:
    name: aap-postgres
  name: gateway
  owner: gateway
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-minimal-trixie
    major: 17
