apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-exporter
  labels:
    app: json-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-exporter
  template:
    metadata:
      labels:
        app: json-exporter
    spec:
      containers:
        - name: json-exporter
          image: quay.io/prometheuscommunity/json-exporter:latest
          args:
            - "--config.file=/config/config.yml"
          ports:
            - containerPort: 7979
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: aap-admin-password
                  key: password
      volumes:
        - name: config-volume
          configMap:
            name: json-exporter-config
