---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-s3-credentials
  namespace: loki
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: loki-s3-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        access_key_id: "{{ .username }}"
        access_key_secret: "{{ .password }}"
        bucketnames: "loki"
        endpoint: "http://minio.loki.svc.cluster.local:9000"
        region: "us-east-1"
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/loki-minio
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ocp-lab/loki-minio
        property: password
